### PR TITLE
fix(preboot): DOM not rendering on browser refresh

### LINKED ISSUE #57: [Issue] when browser refresh, rendered DOM is gone
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [x] server side
- [x] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **What is the current behavior?**
Chrome 60: browser refresh

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
https://github.com/gmanio/ng-ssr

* **What is the expected behavior?**
refresh well

### PR DESCRIPTION
**Pull request by CaerusKaru**
* Remove appRef stability check from event replayer, which could
  be tricked by timers/other stability delays
* Refactor some areas of code that are now type stable
* Bump deps to Angular v5.1 and RxJS v5.5.5

Fixes #57

### CODE REVIEW

**Comment by CaerusKaru** [comment]
cc @jeffwhelpley

**Comment by dneeleman** [comment]
Seems like the buffer is broken for our application since this update. The behaviour with 6.0.0-beta.1 is the same as with 6.0.0-beta.1 with buffer = false.

Result is Angular Universal application to load application, then briefly show a version where the translations are not loaded yet (ngx-translate lib) and then it client side is rendered as expected.

Did I miss a change I need to apply or is this a bug?

**Comment by CaerusKaru** [comment]
@dneeleman Please open a separate issue for this with a minimal reproduction repo, possibly based on the universal-starter. We have no way of debugging this based on present information and this issue has not been reported by others (yet)

**Comment by dneeleman** [comment]
I understand, I will see when I have the time to provide such a project as you might have guessed the code is private for our business. Thank you for the quick reply though!

**Comment by VolodymyrPortiankoJR** [comment]
I think change for not checking appRef.isStable() is broke transition.
eventReplayer.replayAll() is fired too early, many ngOnInit is not executed yet and forms are not initialized properly.

**Comment by CaerusKaru** [comment]
@VolodymyrPortiankoJR That was my first guess, too, but we still need a minimal reproduction and separate issue before we revert anything.

**Comment by dneeleman** [comment]
@CaerusKaru Unfortunately I haven't found time to dissect/minimize our application yet. For now I reverted back to beta 0.

**Comment by VolodymyrPortiankoJR** [comment]
@CaerusKaru Ok, i will try to make simple reproduction. 
But from what i debugged so far, i can see that issue is with lazy loaded modules. APP_BOOTSTRAP_LISTENER is fired when main module is fully loaded, but lazy loaded modules are still in progress.

**Comment by CaerusKaru** [comment]
So here's what I've settled on:

* In order to maintain parity with previous iterations, I've restored the original behavior from beta.0
* To satisfy those who wanted the change in beta.1, I've added the workaround of setting `buffer: false` to achieve their desired behavior

This is consolidated in PR #62, so please test it out and let me know if it meets your needs.

**Comment by CaerusKaru** [comment]
More developments in the revert, in order to achieve the desired behavior, you must follow these steps:

1. Set `noReplay: true`
2. Add a provider to your `AppModule` with the following signature:

```typescript
export function prebootHook(eventReplayer: EventReplayer) {
	const res = () => eventReplayer.replayAll();
	return res;
}

{
	provide: APP_BOOTSTRAP_LISTENER,
    useFactory: prebootHook,
	deps: [EventReplayer],
	multi: true
}
```

We're reverting this because tying the behavior to the buffer settings was not practical.

**Pull request merged**
