### PR TITLE
fix: revert to wait for app stability if buffering

### LINKED ISSUE #63: Object doesn't support property or method 'from': IE11
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [x] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
On IE11, Win 10. The following code will give a 'error: Object doesn't support property or method 'from''. It is part of the inline script.

`
// we want to add an event listener for each node and each event
for (var _i = 0, _a = Array.from(nodes); _i < _a.length; _i++) {
        var node = _a[_i];
        _loop_1(node);
    }`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Just refresh the webpage with debugger catching the error.

* **What is the expected behavior?**
The error should not be there.

* **What is the motivation / use case for changing the behavior?**
I am debugging a problem where the whole <app> node is deleted when client tries to bootstrap, leaving the webpage a solid white screen. This happens 9/10 times after refresh, on IE10/11/Edge, but sometimes also on Safari.

* **Please tell us about your environment:**

- Browser: [IE 11 ]
- Language: [ ES5 ]
- OS:  [ Mac OS X ]
- Platform: [browser]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

### LINKED ISSUE #66: Events not replaying due to mismatched server/client nodes
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [x] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **What is the current behavior?**
Preboot (v. 6.0.0-beta.1) will not replay events on the client-side because client and server nodes do not match. When specifying the `eventSelectors`, getting the following warnings:

`nothing found for INPUT#money-input so using INPUT`

`No matching client node found for INPUT_app-root_s2_s5_s1_s2_s2_s1_s1_s2_s2. You can fix this by assigning this element a unique id attribute.`

and 

`Trying to dispatch event keydown to node INPUT_app-root_s2_s5_s1_s2_s2_s1_s1_s2_s2 but could not find client node. Server node is: [...] `

image

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Repo for the project can be found here: https://github.com/kaitlynekdahl/universal-check-app/tree/master.
1. Clone the project and run `npm install`
2. Run `npm run start-universal` to run the application with SSR
3. Navigate to localhost:3000 and open devtools
4. Under the network tab, set the network throttling to a slower connection (2G or 3G) and hard-refresh the page
5. While the server-side page is displayed and client is loading, enter a number in the input field and press enter on the keyboard (there are some dummy callbacks to show that the events are being recorded on the server-side)
6. Expected behavior is for page to freeze until client is bootstrapped, then events to be replayed (including form submission upon enter), but the warnings above will print the console and events will not replay.

* **What is the expected behavior?**
Client and server nodes _should_ match. The input element in question has a unique ID called `#money-input` (not sure where  `INPUT_app-root_s2_s5_s1_s2_s2_s1_s1_s2_s2` is coming from?) and events should replay upon client bootstrap.

* **Environment:**

- Browser: all
- Language: TypeScript 2.4.2/Angular 5.0.0
- OS:  Windows 
- Platform: NodeJs

* **Other information** 
Could this maybe be a Material or minification thing? I tried using Material directives for the event selectors, but that didn't help.

Might be worth mentioning that I tried with an older version of Preboot (5.1.7) and got the keypress events to replay except for the enter key/form submission. That version had no problems with Angular 4 either.

At this point, any info on this is appreciated.

### PR DESCRIPTION
**Pull request by CaerusKaru**
* Partial revert of #60 due to issues with lazy loading
* Add linting rules and refactor files accordingly
* Bump deps to Angular v5.2 and TypeScript v2.6
* Resolve IE issues by removing Array.from and Element.remove
  references
* Remove Renderer2 references from preboot provider

Fixes #63
Fixes #66

### CODE REVIEW

**Comment by CaerusKaru** [comment]
@jeffwhelpley

**Comment by jeffwhelpley** [comment]
@vikerman a reminder to either review this PR yourself or get me access back the preboot repo.

**Comment by mgol** [comment]
I confirm this PR makes Preboot work for me. Making it work with AngularJS requires more changes but not much more!

Any roadblocks to land it? It'd like to submit a PR improving the ngUpgrade integration.

**Comment by jeffwhelpley** [comment]
@mgol that is great news! @CaerusKaru I have already reviewed this as well and am fine with it going in. I will slack you to coordinate.

**Pull request merged**
