### PR TITLE
fix: angular 6 support

### PR DESCRIPTION
**Pull request by wapisgroup**
update package.json by angular & rxjs 6 libraries, change PrebootSelection interface's direction property type to 'forward' | 'backward' | 'none'. Change in one of the tests to start using 'backward' instead 'reverse' as a value for direction. Remove rxjs/operators from tslint blacklist and add rxjs/operators into karma packages

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/preboot/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What modules are related to this pull-request**
- [x] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [x ] tests

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
remove unused proxy imports from some test files
Angular 6 migration

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/angular/preboot/issues/85

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by wapisgroup** [comment]
I signed it!

**Comment by wapisgroup** [comment]
I signed it!

**Comment by wapisgroup** [comment]
I signed it!

**Comment by CaerusKaru** [comment]
@wapisgroup Thank you so much for this PR. You got almost everything needed to upgrade to Angular v6. Unfortunately it was easier for me to just make these changes myself in #87 than it was to give you some feedback (feel free to check it out to see the differences). Please don't let this discourage you from contributing in the future!

**Pull request closed without merging**
