### PR TITLE
build(ts declarations): Update to generate declaration files and only…

### PR DESCRIPTION
**Pull request by zakhenry**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/preboot/blob/master/CONTRIBUTING.md#commit-message-format
- [na] Tests for the changes have been added (for bug fixes / features)
- [na] Docs have been added / updated (for bug fixes / features)

* **What modules are related to this pull-request**
- [ ] server side
- [ ] client side
- [ ] inline
- [x] build process
- [ ] docs
- [ ] tests

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
remove unused proxy imports from some test files
Build fix, adds `d.ts` file to the output, removes source files

* **What is the current behavior?** (You can also link to an open issue here)
Source files are included which causes issues with TS2.0

* **What is the new behavior (if this is a feature change)?**
`d.ts` only files are distributed which works with the newer TS2.x typings resolution style

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Shouldn't unless they're doing something wild like including from `/src` directly

* **Other information**:

### CODE REVIEW

**Comment by zakhenry** [comment]
Also I note that the output of the tsc is different to what is in the committed `/dist`. Why is dist committed anyway? Possibly something to clean up in this PR too

**Comment by jeffwhelpley** [comment]
I pushed in a change that includes manually generated TS for right now, but I think this is a better solution to get in soon. The only reason I hesitated on this is that in package.json currently you can only reference one TypeScript definition file. This script will generate one definition for each of the generated JS files. So...should we potentially have the preboot.d.ts that I just checked into the root point to dist/node/preboot_node.d.ts and dist/browser/preboot_browser.d.ts?

**Comment by zakhenry** [comment]
@jeffwhelpley I've updated the PR to correctly reference the `preboot.d.ts` file from the package.json, note that it is actually generated from `./src/preboot.ts`, which matches the best practice pattern of never hand-crafting `d.ts` files when a ts source exits

**Comment by zakhenry** [comment]
This PR can be tested with the following in package.json:
```
"preboot": "https://github.com/zakhenry/preboot/releases/download/v4.0.4/preboot-4.0.4.tgz",
```

**Comment by jeffwhelpley** [comment]
@zakhenry sorry to do this to you. Can you please just update your PR with the latest and then I will merge it right in. Really sorry about the extra work. Totally my fault.

**Comment by zakhenry** [comment]
@jeffwhelpley ok done, I had to make a change from using gulp-typescript to just using native childprocess.spawn to use the included typescript directly. This is actually cleaner as removes the intermediary dependency between preboot and typescript. It also means that if you happen to prefer your in-ide typescript compiler it will work perfectly as all the config is in the tsconfig.json

**Comment by jeffwhelpley** [comment]
Hey, @zakhenry finally have time now that AngularConnect is over to loop back on everything. It seems like this PR is not needed anymore with the latest changes, but check it out and let me know if you think we still need some TypeScript definition changes.

**Comment by zakhenry** [comment]
Ah yea I think there probably still is a need for the toolchain to generate the d.ts files and pushed to npm rather than them being committed. I'll have another look at what has been done in the interim and reopen if I see a solution

**Pull request closed without merging**
